Repository valohai/django-allauth-2fa, pull requests merged in 2022-07, with the labels that each got.

#141 Clean up URLs
  allauth_2fa/urls.py
  docs/installation.rst
  tests/test_allauth_2fa.py
  tests/urls.py
Labels: tech debt, enhancement

#146 Use f-strings instead of concatenation
  allauth_2fa/adapter.py
  allauth_2fa/views.py
  tests/test_allauth_2fa.py
Labels: tech debt

#145 Allow customizing view success URLs via app_settings
  allauth_2fa/app_settings.py
  allauth_2fa/views.py
  docs/configuration.rst
Labels: enhancement

#144 Don't try to interrogate function-based views for `next`
  allauth_2fa/adapter.py
Labels: bug

#109 Show secret on setup.html to allow for manual entry for multiple yubikeys & other devices
  allauth_2fa/templates/allauth_2fa/setup.html
  allauth_2fa/utils.py
  allauth_2fa/views.py
Labels: enhancement
